### PR TITLE
cups: move files upstream

### PR DESCRIPTION
**Pull request by pkillarjun**
Move my fuzzing harness upstream. I was unable to update https://github.com/OpenPrinting/fuzzing/pull/1.
Also, update the `libcups` directory path.

Problems:
* I didn't test the build on Fedora.
* I haven't tested the `oss-fuzz.sh` file.

### CODE REVIEW

**Comment by pkillarjun** [comment]
I will delete this if I can update the files in https://github.com/OpenPrinting/fuzzing/pull/1.

**Comment by fish98** [comment]
> I will delete this if I can update the files in #1.

I have updated the access. I think we can go with this PR too if there are any inconvenience for the prior PR.

**Comment by pkillarjun** [comment]
> > I will delete this if I can update the files in #1.
> 
> I have updated the access. I think we can go with this PR too if there are any inconvenience for the prior PR.

I can't update that PR. I need to add a `README.md` in the `cups` directory. When it's done, I will ping you.

**Comment by pkillarjun** [comment]
Thank you for the invitation. I am closing this now.

**Pull request closed without merging**
